# -*- coding: utf-8 -*-
"""Python Temel Proje Ödevi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gtqUjPNdUoMrhdGv15ozvIn2aL1e_EX2
"""

#1. Bir listeyi düzleştiren (flatten) fonksiyon yazın. Elemanları birden çok katmanlı listtlerden ([[3],2] gibi) oluşabileceği gibi, non-scalar verilerden de oluşabilir. Örnek olarak:
#ornek: [[1,'a',['cat'],2],[[[3]],'dog'],4,5]

#sonuc: [1,'a','cat',2,3,'dog',4,5]

flat_l = []

def flat_list(l):

  for i in l:
    if type(i) == list:
      flat_list(i)
    else:
      flat_l.append(i)
  return flat_l

ornek = [[1,'a',['cat'],2],[[[3]],'dog'],4,5]
print('Original List', ornek)
print('Flat List', flat_list(ornek))

#2. Verilen listenin içindeki elemanları tersine döndüren bir fonksiyon yazın. Eğer listenin içindeki elemanlar da liste içeriyorsa onların elemanlarını da tersine döndürün. Örnek olarak:
#input: [[1, 2], [3, 4], [5, 6, 7]]
#output: [[[7, 6, 5], [4, 3], [2, 1]]

def reverse_list(l):
    rev_list = list(reversed(l))
    a = 0
    for i in rev_list:
        if type(i) == list:
            rev_list[a] = list(reversed(i))
            a = a+1
        else:
            a = a+1
    return rev_list

input = [[1, 2], [3, 4], [5, 6, 7]]
print('Reversed List', reverse_list(input))